name: marful
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.0-109.0.dev <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  signalr_core: ^1.1.1
  flutter: 
    sdk: flutter
  q_overlay: 
    git: https://github.com/SchabanBo/q_overlay.git

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

