name: marful
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.17.1<3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.3
  signalr_core: ^1.1.1
  dio: ^4.0.6
  flutter: 
    sdk: flutter
  q_overlay: 
    git: https://github.com/SchabanBo/q_overlay.git
  introduction_screen: ^3.0.1 
  flutter_svg: ^1.0.3 
  image_picker: ^0.8.5+3

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
   - assets/images/
  fonts:
   - family: MyFlutterApp
     fonts:
       - asset: assets/fonts/MyFlutterApp.ttf 
   
   
